### ISSUE TITLE
Task pane opens with index page that is mostly blank & no Calendar data

### ISSUE THREAD

**Issue by SoftEngrLACA** [OfficeDev/Word-Add-in-AngularJS-Client-OAuth#4]
Ran the add-in: > inside Word 2016 > choose My Add-ins, then select SHARED FOLDER > Selected Client-Side Auth Sample, then choose OK.
The task pane opens and shows the index page that is mostly blank and no other log in prompts to access Calendar data.

Implementation details:

After registering the app in Microsoft Azure using the new Azure portal, there is **no client ID generated**. **Only Application and Object IDs are generated**. We assumed that the client ID is Application ID. The app inside Azure portal is identified by this Application ID.

Deployed the folder ‘Word-Add-in-AngularJS-Client-OAuth’ and its contents to Amazon S3 server that we use to serve static content. The `index.html`, `Auth.html` and `./scripts/azureADConfig.js` are accessible from a browser. Therefore did not use gulp.

Used the above Application ID to update the script azureADConfig.js’s field ‘clientId’.

Had to change resources in folder to “./”, example `<script src="./scripts/azureADConfig.js"></script>
`.

Thank you for any help in resolving this.

**Comment by Rick-Kirkham** [comment]
I feel your pain, but the AAD portion of the new Azure portal is still in preview, so our sample add-ins must use the existing portal. You could try using the object ID as the client ID. And/or be sure that you are requesting the needed permissions to AAD and MS Graph in the new portal and that you have both of the allowed Reply URLs registered in the new portal. Also, you could try running the Fiddler tool and see if the raw replies give any clue as to why the data doesn't load. 

If none of that works, please follow the readme's instructions _exactly_ and see if you get the same symptoms.

**Comment by SoftEngrLACA** [comment]
Thanks for the reply. I will try this out.

```
  From: Rick-Kirkham <notifications@github.com>
```

 To: OfficeDev/Word-Add-in-AngularJS-Client-OAuth Word-Add-in-AngularJS-Client-OAuth@noreply.github.com 
Cc: SoftEngrLACA wick_sw_engineer@yahoo.com; Author author@noreply.github.com
 Sent: Wednesday, October 5, 2016 11:39 AM
 Subject: Re: [OfficeDev/Word-Add-in-AngularJS-Client-OAuth] Task pane opens with index page that is mostly blank & no Calendar data (#4)

I feel your pain, but the AAD portion of the new Azure portal is still in preview, so our sample add-ins must use the existing portal. You could try using the object ID as the client ID. And/or be sure that you are requesting the needed permissions to AAD and MS Graph in the new portal and that you have both of the allowed Reply URLs registered in the new portal. Also, you could try running the Fiddler tool and see if the raw replies give any clue as to why the data doesn't load. If none of that works, please follow the readme's instructions exactly and see if you get the same symptoms. —
